CREATE TABLE users(
  id VARCHAR(255) PRIMARY KEY DEFAULT(UUID()),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  email_verified DATETIME,
  image VARCHAR(255),
  hashed_password VARCHAR(255) NOT NULL,
  user_type ENUM('User','Admin') DEFAULT 'User',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sessions(
  id VARCHAR(255) PRIMARY KEY DEFAULT(UUID()),
  session_token VARCHAR(255) UNIQUE NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  expires DATETIME NOT NULL,
  CONSTRAINT fk_session_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);